project:
  type: website

website:
  title: "GISproject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction
      - href: Method.qmd
        text: Methodology
      - href: Analysis.html
        text: Analysis
      - href: finding.qmd
        text: Results & Discussion
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

